using '../unit9-migration.bicep'

param location = 'francecentral'
param replacementContainerAppsEnvironmentName = 'nsrsdp-dev-network-cae'
param replacementJobName = 'nsrsdp-dev-transform-job-vnet'
param acrName = 'nsrsdpdev2gndgslsp4a6cacr'
param acrPullIdentityName = 'nsrsdp-dev-transform-acr-pull-mi'
param imageName = 'nsrsdp-dev-transformation:unit7-13cd4410b8e2'
param environmentName = 'development'
param storageAccountName = 'nsrsdpdev2gndgslsp4a6cst'
param rawContainerName = 'raw'
param processedContainerName = 'processed'
param curatedContainerName = 'curated'
param quarantineContainerName = 'quarantine'
param cpu = '0.5'
param memory = '1Gi'
param tags = {
  costOwner: 'data-engineering'
  environment: 'development'
  managedBy: 'Bicep'
  portfolio: 'northstar-retail'
  project: 'cloud-data-platform-foundation'
  repository: 'sales-data-platform-azure'
  workload: 'northstar-retail-sales-data-platform'
}
