using '../unit9-private-network.bicep'

param location = 'francecentral'
param virtualNetworkName = 'nsrsdp-dev-unit9-vnet'
param virtualNetworkAddressPrefix = '10.42.0.0/26'
param containerAppsEnvironmentSubnetName = 'container-apps-environment'
param containerAppsEnvironmentSubnetPrefix = '10.42.0.0/27'
param privateEndpointSubnetName = 'postgresql-private-endpoint'
param privateEndpointSubnetPrefix = '10.42.0.32/28'
param replacementContainerAppsEnvironmentName = 'nsrsdp-dev-network-cae'
param postgresqlServerName = 'nsrsdp-dev-2gndgslsp4a6c-pg'
param logAnalyticsWorkspaceName = 'nsrsdp-dev-2gndgslsp4a6c-law'
param postgresqlPrivateEndpointName = 'nsrsdp-dev-postgresql-pe'
param postgresqlPrivateLinkConnectionName = 'nsrsdp-dev-postgresql-pls-connection'
param privateDnsZoneLinkName = 'nsrsdp-dev-postgresql-vnet-link'
param tags = {
  costOwner: 'data-engineering'
  environment: 'development'
  managedBy: 'Bicep'
  portfolio: 'northstar-retail'
  project: 'cloud-data-platform-foundation'
  repository: 'sales-data-platform-azure'
  workload: 'northstar-retail-sales-data-platform'
}
